login/urls.py
from . import views
from django.conf.urls import url

app_name = 'login'
urlpatterns = [
    # url(r'^upload/', views.upload_csv, name="upload"),
    url(r'^app/', views.index_view, name="index"),
    url(r'^login/', views.login_view, name="login"),
    url(r'^logout/', views.logout_view, name="logout"),
    url(r'^register/', views.register_view, name="register"),
    url(r'^profile/', views.profile_view, name="profile"),
    url(r'^locations/$', views.display_location)
]

website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("login.urls")),

]

login/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

class UserComplaint(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    complaint = models.CharField(max_length=200)
    location = models.CharField(max_length=200, default="Null")
    Mobile_number = models.IntegerField(max_length=10)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.location

login/views.py
from __future__ import unicode_literals
from .form import UserLoginForm, UserRegisterForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect
from .models import UserComplaint
import datetime, json
import googlemaps
import csv
#key to access google api
api_key = "AIzaSyBb3ERZRNTtb-Rp0FpWsTu7VQmU6OjD5lM"
#home page of the website
def index_view(request):
        return render(request, "login/index.html", {})

#login page 
def login_view(request):
    print "inside login view"
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print username, password, "username and password"
        user = authenticate(username=username, password=password)
        form = User(request.POST)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/profile/')
            else:
                return render(request, 'login/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login/login.html', {'error_message': 'Enter correct username or password'})
    return render(request, "login/login.html", {})

#registration page
@csrf_exempt
def register_view(request):
    title = "Register"
    form = UserRegisterForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        email = form.cleaned_data.get('email')
        usern = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user.set_password(password)
        authenticate(username=user.username, password=password)
        user.is_active = False
        user.save()
        return render(request, "login/index.html", {"title": title, "username": usern})

    context = {
        "form": form,
        "title": title
    }
    return render(request, "login/registration.html", context)

#logout user from his profile to the homePage
def logout_view(request):
    logout(request)
    return render(request, "login/index.html", {})


#profile page for the users
def profile_view(request):
    if request.method == "POST":
        date_time = datetime.datetime.now()
        varr = request.POST
        variablee = "lllllllllllllllllllllllllllllllllllllllllllll"
        print "ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo", varr
        
        data_update = UserComplaint(user=request.user, complaint=varr["complaint"], location=varr["location"], Mobile_number=varr["mobile_number"], pub_date=date_time )
        data_update.save()
        message= "complain has been submitted"
        return render(request, 'login/profile.html', {'msg':message})

    return render(request, 'login/profile.html', {})


def display_location(request):
    print "inside"
    data = UserComplaint.objects.all()
    loc_list =[]
    details_list = []
    for i in data:
        print i.user
        # print i.location
    # print loc_list
    
        gmaps = googlemaps.Client(key=api_key)
        address = i.location
        lat_lng = gmaps.geocode(address)
        # print lat_lng
        loc_list.append([i.location,lat_lng[0]['geometry']['location']['lat'], lat_lng[0]['geometry']['location']['lng']
        ])
        details_list.append([i.Mobile_number, i.complaint, str(i.pub_date)])
    # print loc_list
    print details_list

    test = loc_list

    return render_to_response('login/location.html', {"test":json.dumps(test),"listt":json.dumps(details_list) } )

templates/login/activation.html
{% extends "login/base.html" %}
{% block content %}

<div class="container-fluid bg-grey text-center">
	<h4>Your account is activated successfully!</h4>
</div>
<div class="container-fluid text-center">
	<br><br>
    <h4><a href="/account/login">Login</a></h4>
    <form method="get">
    <button type="submit">Continue</button>
</form>
	<br>
</div>


{% endblock %}

templates/login/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<html>
<head>
    <title>Family Host</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .header {
            background-color: #3399CC;
            color: #fff;
            padding: 80px 25px;
        }

        .footer {
            position: relative;
            margin-top: 0px; /* negative value of footer height */
            height: 0px;
            clear: both;
            padding-top: 120px;
        }
    </style>
</head>
<body style="padding-bottom: 10px">
<div class="header text-center">
    <h1><strong>Chat Bot</strong></h1>
    <br>
    <h4>A description of your brilliant website</h4>
    <h5><a href="{% url 'login:profile' %}">Update Profile</a></h5>
</div>
{% block content %}
{% endblock %}
<div class="footer">
    <div class="row">
        <div class="col-sm-4" style="background-color:#C8E6C9  ;padding-bottom:20px">
            <div class="container">
                <h4> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </h4>
            </div>
        </div>
        <div class="col-sm-4" style="background-color:#C8E6C9  ;padding-bottom:20px">
            <div class="container">
                <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;
                </h4>
            </div>
        </div>
        <div class="col-sm-4" style="background-color:#C8E6C9  ;padding-bottom:20px">
            <div class="container">
                <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </h4>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
        /* Full-width input fields */
        input[type=text], input[type=password], input[type=email], input[type=number] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        /* Set a style for all buttons */
        button {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
        }

        /* Float cancel and signup buttons and add an equal width */
        .signupbtn {
            float: left;
            width: 50%;
        }

        /* Add padding to container elements */
        .container {
            padding: 16px;
        }

        /* Clear floats */
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }

        /* Change styles for cancel button and signup button on extra small screens */
        @media screen and (max-width: 300px) {
            .signupbtn {
                width: 100%;
            }
        }
    </style>
</head>
<body>
<h1>Hello </h1>
<button><a href="/login/">Login</a></button>
<button><a href="/register/">Register</a></button>



</body>
</html>

templates/login/location.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
   <link rel="stylesheet" href="{% static "/css/materialize.css" %}">
    <link rel="stylesheet" href="{% static "/css/materialize.min.css" %}">


  <script src= "{% static "/js/materialize.js" %}"></script>
    <script src= "{% static "/js/materialize.min.js" %}"></script> 
     <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map_wrapper {
    height: 530px;
}

#map_canvas {
    width: 100%;
    height: 100%;
}
    </style>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBb3ERZRNTtb-Rp0FpWsTu7VQmU6OjD5lM&c0allback=initMap"
    async defer></script>
          
</head>
<body onload="initialize()">
<nav>
    
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Python</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
       
        <li><a href="/profile/">Add Complaint</a></li>
      </ul>
    </div>
  </nav>
 <!-- <div class="row">
        <div class="col s12 m12">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                     -->
        <div id="map_wrapper">
            <div id="map_canvas" class="mapping"></div>
        </div>
                    <!-- </div>
           
          </div>
        </div>
      </div> -->
    <script type="text/javascript">
 
      jQuery(function($) {
    // Asynchronously Load the map API 
    
    var script = document.createElement('script');
    script.src = "//maps.googleapis.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(script);
});
function initialize() {
    // var django_data =  }};
alert("hell");
    
    var map;
    var bounds = new google.maps.LatLngBounds();
    var mapOptions = {
        mapTypeId: 'roadmap'
    };
                    
    // Display a map on the page
    map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
    map.setTilt(45);
        
    // Multiple Markers
    var markers = {{ test|safe }};
    
                        
    // Info Window Content
    var infoWindowContent = {{ listt|safe }};
        
    // Display multiple markers on a map
    var infoWindow = new google.maps.InfoWindow(), marker, i;
    
    // Loop through our array of markers & place each one on the map  
    for( i = 0; i < markers.length; i++ ) {
        var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
        bounds.extend(position);
        marker = new google.maps.Marker({
            position: position,
            map: map,
            title: markers[i][0]
        });
        
        // Allow each marker to have an info window    
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infoWindow.setContent(infoWindowContent[i][0],infoWindowContent[i][1],infoWindowContent[i][2],);
                infoWindow.open(map, marker);
            }
        })(marker, i));

        // Automatically center the map fitting all markers on the screen
        map.fitBounds(bounds);
    }

    // Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
    var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
        this.setZoom(6);
        google.maps.event.removeListener(boundsListener);
    });
    
}
    </script> 



</body>
</html> 

templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
 <title>Login Page</title>
<style>
    /* Full-width input fields */
input[type=text], input[type=password], input[type=email] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

/* Extra styles for the cancel button */
.cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn,.signupbtn {
    float: left;
    width: 50%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

/* Clear floats */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
        width: 100%;
    }
}
</style>
</head>
<body>
        <a href="/app/">Home</a> <br>
        <a href="/register/">Register</a>
        Click here if you are not registered »
        
<h3>Log In</h3>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post">{% csrf_token %}
  <div class="container">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter username" name="username">


      <label><b>Password</b></label>
    <input type="password" placeholder="Password" name="password">

    <div class="clearfix">
      <button type="submit" class="signupbtn">Login</button>
    </div>
  </div>
</form>
</body>
</html>

templates/login/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
        /* Full-width input fields */
        input[type=text], input[type=password], input[type=email], input[type=number] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        /* Set a style for all buttons */
        button {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
        }

        /* Float cancel and signup buttons and add an equal width */
        .signupbtn {
            float: left;
            width: 50%;
        }

        /* Add padding to container elements */
        .container {
            padding: 16px;
        }

        /* Clear floats */
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }

        /* Change styles for cancel button and signup button on extra small screens */
        @media screen and (max-width: 300px) {
            .signupbtn {
                width: 100%;
            }
        }
    </style>
</head>
<body>

<h1>Profile</h1>
<h2><a href="{% url 'login:logout' %}">Logout</a> </h2>
{{ msg }}
<form action="/profile/" method="post">{% csrf_token %}
    

    <input type="text" name="complaint" placeholder="Enter your complain here">
    <input type="text" name="location" placeholder="your location/Address" >
    <input type="text" name="mobile_number" placeholder="Contact">
    <!-- <input type="text" name="pub_date" > -->
    <br><br>
    <input class="waves-effect waves-light btn" type="submit" value="Submit">
    
</form>
<!-- {{ profile }} -->
</body>
</html>

templates/login/registration.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
 <title>Registration Page</title>
<style>
    /* Full-width input fields */
input[type=text], input[type=password], input[type=email] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

/* Extra styles for the cancel button */
.cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn,.signupbtn {
    float: left;
    width: 50%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

/* Clear floats */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
        width: 100%;
    }
}
</style>
</head>
<body>
        <!-- <img src="{% static 'images/test_image.gif' %}"> -->
<h1>{{ title }}</h1>
<a href="/app/">Home</a><br>

<a href="/login/">Login</a>
Click here if you are already registered »

<form action="" method="POST">{% csrf_token %}
  <div class="container">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter username" name="username">
    <label><b>First name</b></label>
    <input type="text" placeholder="Enter First name" name="first_name">
    <label><b>Last Name</b></label>
    <input type="text" placeholder="Enter Last name" name="last_name">

      <label><b>Email</b></label>
    <input type="email" placeholder="Enter Email" name="email">

      <label><b>Confirm Email</b></label>
    <input type="email" placeholder="confirm email" name="email2">


      <label><b>Password</b></label>
    <input type="password" placeholder="Password" name="password">

    <div class="clearfix">
      <button type="submit" class="signupbtn">{{ title }}</button>
    </div>
  </div>
</form>
</body>
</html>